# Generated by Django 3.0.2 on 2020-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200829_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='countlikes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
