# Generated by Django 3.1 on 2020-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='make_private',
            field=models.BooleanField(default=False),
        ),
    ]
